development:
  adapter: async

test:
  adapter: async

# production:
#   # adapter: redis
#   # url: redis://localhost:6379/1
#   adapter: redis
#   url: <%= ENV["REDISCLOUD_URL"] %>

production: &production
  :url: redis://redistogo:5888ff2df81922e441c2df359fd9ee7d@koi.redistogo.com:10658/
  :host: tarpon.redistogo.com
  :port: 10658
  :password: 5888ff2df81922e441c2df359fd9ee7d
  :inline: true
  :timeout: 1
